platform :ios, "8.0"
use_frameworks!

pod "WatchdogInspector", :path => "../WatchdogInspector.podspec"

target "SwiftExampleTests" do
  pod 'WatchdogInspector', :path => "../WatchdogInspector.podspec"
end
