use_frameworks!

target "SwiftExample" do
  pod 'WatchdogInspector', :path => "../WatchdogInspector.podspec"
end

target "SwiftExampleTests" do
  pod 'WatchdogInspector', :path => "../WatchdogInspector.podspec"
end

target "SwiftExample_tvOS" do
    pod 'WatchdogInspector', :path => "../WatchdogInspector.podspec"
end
